### ISSUE TITLE
[OJS] orcidProfile writes empty URI after failed auth

### ISSUE THREAD

**Issue by SKhoo** [pkp/orcidProfile#113]
Hello

I recently encountered a problem with the orcidProfile plugin. After sending an authentication request email to an author without an account in the system, I found that their metadata had an empty orcid.org URI. They said that they were able to log into their account to authenticate their orcid, but got an error message saying the link had expired. From my orcid.log:

> 2019-06-30 21:19:15.240 INFO Request body: grant_type=authorization_code&client_id=APP-XXXXXX&client_secret=XXXXXXXXXXXXXXX
> 2019-06-30 21:19:16.240 INFO Response body: {"error":"server_error","error_description":"An authorization code must be supplied."}
> 2019-06-30 21:19:16.240 ERROR Response status: 500 . Invalid ORCID response: {"error":"server_error","error_description":"An authorization code must be supplied."}
> 2019-06-30 21:19:41.202 ERROR OrcidHandler::orcidverify - No author found with supplied token
> 2019-06-30 21:20:39.056 ERROR OrcidHandler::orcidverify - No author found with supplied token
> 2019-07-01 10:07:50.536 INFO POST https://pub.orcid.org/oauth/token
> 2019-07-01 10:07:50.538 INFO Request header: array (
>   0 => 'Accept: application/json',

Once this happened, I couldn't remove the bad orcid data without disabling the orcid plugin because I would get an error message saying the orcid was invalid and needed to be corrected. However, disabling the orcid plugin allowed me to delete the orcid on the article's metadata.

I am using OJS 3.1.2.1 and orcidProfile v 1.1.1.1.

Thanks for your help

**Comment by librariam** [comment]
@withanage do you think this could be addressed in upcoming plugin updates? We are getting a number of tickets related to this bug in PKP|PS. Please see my comments in #115 - thank you!

**Comment by librariam** [comment]
Hi @withanage we are currently seeing the issue in 3.2.0.2.

It appears it's not possible to rectify the issue by removing and recreating the contributor and having them complete ORCID authorization again - the empty URL keeps being written into their contributor profile. I guess disabling the ORCID plugin to write the URL manually and then enabling it again as described above is the only interim solution, unless you would have other recommendations?

**Comment by librariam** [comment]
We have received a report from a 3.2.1.2 journal of 5 authors encountering the same problem. The plugin version is 1.1.2.20 and it's the latest that it could be upgraded to.

**Comment by asmecher** [comment]
Assigning you for a look, @withanage!

**Comment by withanage** [comment]
@librariam  coming back from holidays. Will add a update to this in the next release.

**Comment by withanage** [comment]
@librariam

I have gone through this problem and found 2 issues, which created the problem.
1. Deleting a sandbox id is not allowed in OJS (main OJS code)
2. Redirect URL does not include the publication id (in some cases, depending on the browser)

#
1. I had already fixed the [Sandox url issue](https://github.com/pkp/pkp-lib/commit/687550f052ea291d7010d959258e4998efa8a913#diff-d825c588dc7cdd8c10f31ddee9b76d584f356060bfa8591d4a289532236d5213)
in  May 2021. But  this is not included in a major release, cause the latest OJS release is https://github.com/pkp/ojs/releases/tag/3_2_1-4 from Feb.2021

Will ask  @asmecher if it makes sense to do a OJS 3.2.1 minor release for this.

2. This was the most complex one to find the reason, cause it worked in production and in some browsers and failed in  unkown circumstances.

I have released the plugin for OJS 3.2.1 , but  did not integrate as the travis tests did not run.
Will do in the coming days. https://github.com/pkp/orcidProfile/releases/tag/v1_1_2-26

Other versions  will follow  in the coming days.

##### Reason for technical documentation

OAuth protocol  only allows a parameter names **state**  https://datatracker.ietf.org/doc/html/rfc6749#section-4.1.1
and   the publicationId is  cut away automatically.

**Comment by librariam** [comment]
@withanage I wanted to double-check whether I understood correctly that the issue with ORCID writing partial URL was fixed in the v1.1.2.26 release? We are getting reports from journals on that version that it's still an issue. It's the latest version compatible with 3.2.1 but we can recommend an upgrade to 3.3 if there's a fix in a later release - thank you for clarifying.

**Comment by withanage** [comment]
@librariam 
> @withanage I wanted to double-check whether I understood correctly that the issue with ORCID writing partial URL was fixed in the v1.1.2.26 release? 

Actually, they  don need a OJS update to get the partial URL problem to be fixed.  Can you point me offline to an  one use case. In some rare occations, I had the issue that some university email clients encrypt the URLs and the decryption is led to an issue of registering. Wanted to rule out that is not the case.

**Comment by withanage** [comment]
@librariam 
Hi Mariya,
I have released a plugin  addresseing this issue.
https://github.com/pkp/orcidProfile/releases/tag/v1_1_2-28

Best,
Dulip

**Comment by withanage** [comment]
Hi @librariam  could you test the new version ?
