### ISSUE TITLE
ORCID Plugin enhancements for OJS 3.1.2  and beyond

### ISSUE THREAD

**Issue by withanage** [pkp/orcidProfile#115]
Following issues and enhancement requests are related, currently being developed or in discussion for the OJS 3.1.2 and 3.2 + support.

Description | Issue | Status  | area |
-- |-- | -- | -- 
 |Issue publish | pkp/pkp-lib#5572| :ok:  | Issue | 
| Sandbox iDs | pkp/pkp-lib#4893 | :ok:  | Issue | 
| datacite export |  pkp/pkp-lib#4903  | :construction:  | Issue| 
| Empty URI after failed auth | pkp/orcidProfile#113 |:construction:  | Issue| 
| icon problem | https://forum.pkp.sfu.ca/t/orcid-icon-problem/53637|:construction:  | Forum| 
| icon problem | https://forum.pkp.sfu.ca/t/ojs-3-1-2-1-orcid-icon-doesnt-show/54613 |:construction:  |Forum| 
| Option for emails| pkp/orcidProfile#112 | :construction: | Issue |

**Comment by librariam** [comment]
+1 from PKP|PS re #113 - encountered it on 3.2.1.1 (not sure of the ORCID plugin version at the time since I updated it to v1.1.2.6 after the bug happened).

**Comment by librariam** [comment]
+1 more from PKP|PS re #113 on 3.1.2.4, plugin v. 1.1.1.5
An added consequence here is that the incomplete URL in the ORCID iD field breaks Crossref XML export. There is no easy way to remove it without disabling the plugin.

**Comment by withanage** [comment]
Hi  @librariam ,
Thanks for the info.
I will look  into this issue in the next release.

**Comment by bibliothekswelt** [comment]
When an article is pushed to my ORCID profile via the ORICD plugin, it seems to be, that only the URL of the article is transmitted but not the DOI. Is it possible to transmit the DOI, too? We are synchronyzing our local repository with ORCID (for users which have an ORCID iD) but we are only using the DOI for this mechanism. If an article gets pushed to an ORCID profile it can make it's way to our local repository automatically when there's a DOI for the record in ORCID. It would be great, if the DOI can be added.

**Comment by librariam** [comment]
+1 more from PKP|PS re #[113 ](https://github.com/pkp/orcidProfile/issues/113) on 3.2.0.2, plugin v. 1.1.2.3

**Comment by librariam** [comment]
@withanage do you have any update on #[113 ](https://github.com/pkp/orcidProfile/issues/113)? We get reports about it from editors fairly regularly and it's a pain to deal with after the partial URL is recorded. Thank you for taking a look!

**Comment by ej2432** [comment]
Hi, @withanage and all. Where should enhancement requests for this plugin be sent or posted? Specifically, several of our journals are interested in being able to credit peer reviewers through the plugin. Thanks for your guidance.

**Comment by withanage** [comment]
@librariam  #113 is closed. Closing this meta issue.
