### ISSUE TITLE
Add pre-publication check to prevent publishing unauthenticated ORCID ids

### ISSUE THREAD

**Issue by NateWr** [pkp/orcidProfile#119]
**Is your feature request related to a problem? Please describe.**
When an ORCID has been provided for an author, that ORCID should be authenticated. Editors may accidentally publish a submission without checking that all provided ORCID ids have been authenticated.

**Describe the solution you'd like**
v3.2 provides support for [pre-publication checks](https://forum.pkp.sfu.ca/t/what-pre-publication-checks-would-you-like-to-see/59163). It would be nice if the plugin had an option to enforce authenticated IDs in the plugin settings. When checked, a submission would use a pre-publication check to prevent a publication from being published if an ORCID id has been added but not authenticated.

**Comment by withanage** [comment]
Support added and merged
