### ISSUE TITLE
Add documentation on how to remove an ORCID iD that had been previously connected to an OJS author profile.

### ISSUE THREAD

**Issue by sheilarabun** [pkp/orcidProfile#121]
I had a really hard time finding documentation for how to remove an ORCID iD once one has already been connected to an author profile in OJS. (in my case, I was helping someone who had connected a sandbox ORCID iD to their actual OJS profile in order to test the plugin) I put together a tutorial with screenshots, please feel free to incorporate this into existing documentation: https://docs.google.com/document/d/1F9j6W3h8SFwaJ4D4RR1q4VK8rlLZ0Y4JxJNg75wc6p0/edit?usp=sharing

**Comment by xmlFlow** [comment]
Hi @sheilarabun ,

thanks a lot for this documentation, I will incorporate it in the orcid profile doucmentation.

**Comment by withanage** [comment]
Hi @sheilarabun ,

thanks a lot for this documentation, I will incorporate it in the orcid profile doucmentation.
