### ISSUE TITLE
[OPS] Authors can't associate ORCID ID after preprint is posted

### ISSUE THREAD

**Issue by alexxxmendonca** [pkp/orcidProfile#127]
**Describe the bug**
After a preprint is posted, authors are unable to associate their ORCID ID to the metadata.

They see the following message after they click on the deeplink sent by e-mail:

![image](https://user-images.githubusercontent.com/4059679/80015813-a670bd80-84a8-11ea-8a03-05636845f072.png)

**To Reproduce**
1. Submit a preprint.
2. Add co-authors; do not associate co-authors' ORCID IDs
3. As a moderator, send the ORCID ID request e-mail to co-authors
4. Post preprint.
5. As the co-author, attempt to associate your ORCID ID by clicking on the deeplink sent on e-mail of step 3.
6. See error.

**What application are you using?**
Open Preprint Systems 3.2.0.1

**Additional information**
Preprints have a very fast workflow. They get either rejected or approved often within 24 hours. Often times, between screening and actual posting of preprint, there is not enough time for all co-authors to associate their ORCID IDs. The platform should still allow ORCID association after-posting. The deeplinks should still be valid.

On that note, it would be good if, as a Moderator, I could re-send the ORCID validation email for a given posted preprint. After you post a preprint, the moderator can no longer send this e-mail. Sometimes the author miss the email. It would be nice to be able to send it again (I'm happy to open a new issue of that's the case).

**Comment by ajnyga** [comment]
Thanks @withanage 

Ok, I did not notice that it uses the citation plugin. There is now working version of the Citation Style Language Plugin or OPS, it has not been ported yet.

**Comment by withanage** [comment]
@ajnyga
Was there any update in the OPS for the citation plugin during the last days ?

**Comment by alexxxmendonca** [comment]
@withanage the Citation Style Language Plugin plugin has been ported to OPS by the folks of Lepidus. We've been using it for a while now.

**Comment by asmecher** [comment]
@withanage, do you know what version of the ORCiD plugin this was released in? It's filed against 1.1.2-29, but I don't think there ever was a version released like that.

**Comment by alexxxmendonca** [comment]
Hi @asmechand @withanage,

I can confirm that this issue has been solved and authors are able to associate their ORCID IDs even after a preprint is posted.

I will close the issue.

**Comment by asmecher** [comment]
Great, thanks for confirming, @alexxxmendonca!
