### ISSUE TITLE
400 Bad request: invalid JSON

### ISSUE THREAD

**Issue by dagosalas** [pkp/orcidProfile#131]
Hi !
I´m using ORCID membership, everything works fine, authorization, permissions etc. Only when an article is published, the plugin does not push orcid register and log file shows the following:

ERROR Unexpected status 400 response, body: {"response-code":400,"developer-message":"400 Bad request: invalid JSON - cvc-pattern-valid: Value '' is not facet-valid with respect to pattern '[\\s\\S]*[^\\s\\n\\r]+[\\s\\S]*' for type '#AnonType_translated-title'.","user-message":"Invalid JSON.","error-code":9047,"more-info":"https://members.orcid.org/api/resources/troubleshooting"}

OJS 3.2.0.3
PHP 7.3
Debian 9

**Comment by asmecher** [comment]
@dagosalas, I see you've also posted this [on the support forum](https://forum.pkp.sfu.ca/t/ojs-3-2-0-3-orcid-400-bad-request-invalid-json/60587); let's discuss it there, and if it results in a confirmed bug, it can move here. (It's best to just post in one place.)

**Comment by dagosalas** [comment]
I think those null values are the problem.
 
![Screenshot 2020-05-16 00 31 04](https://user-images.githubusercontent.com/21068555/82111856-7619e900-970d-11ea-87b7-e2b804b21314.png)
