### ISSUE TITLE
When using the sandbox API, the ORCID validator can't validate

### ISSUE THREAD

**Issue by jmacgreg** [pkp/orcidProfile#142]
A regular ORCID ID looks like this (and must include the URL): 

https://orcid.org/0000-0003-3530-156X

When a journal uses the sandbox options with the ORCID plugin, the ORCID IDs become: 

https://sandbox.orcid.org/0000-0003-3530-156X

However the ORCID field validator isn't written to permit the inclusion of "sandbox" in the ID string. It should permit this option, only when the sandbox options are being used.

**Comment by davidjb** [comment]
I've noticed this when testing this plugin on OJS 3.3; saving any forms with ORCID iD fields on them (e.g Profile -> Public; Edit User) fail to save, requiring the ORCID iD field to be a maximum of 37 characters, the length of the URL without the `sandbox.` prefix.

**Comment by withanage** [comment]
@davidjb  the lengh of the orcid ids are counfigured in ojs. I will take this into account in the next release.

**Comment by withanage** [comment]
Hi @davidjb ,

This needed changes to main OJS pkp-lib library and the plugin code base. I have requested a review from @asmecher .
As soon as he has reviewed , I  will  integrate the  changes and release appropriate versions OJS/OPA 3.3.0, 3.3.1 and OJS/O
PS 3.2.1 
Please bear with me, that the plugin will be relased, after the  ORCID API 3 update.  https://github.com/pkp/orcidProfile/issues/171
