### ISSUE TITLE
Authenticated ORCIDs may display double icon

### ISSUE THREAD

**Issue by jmacgreg** [pkp/orcidProfile#144]
**Describe the bug**
Originally filed at https://github.com/pkp/classic/issues/82. If an author authenticates their ORCID iD against a submission, the ORCID iD icon should display next to their name. But in this case, it will display twice.

**To Reproduce**

    Enable ORCID plugin
    ask an author to authenticate their ORCID iD
    publish the article

**Screenshots**
<img width="329" alt="image" src="https://user-images.githubusercontent.com/201446/89299659-fda03580-d634-11ea-9b8f-c2e912655fd5.png">

**Solution** 
The problem is that the plugin displays an SVG icon, and also renders the icon in JS. The SVG icon can be repressed in themes, but it looks like the JS is added via this plugin (see templates/authorOrcidForm.tpl, lines 28-47 I think?). My original proposed solution was to remove the SVG file, but @NateWr suggests otherwise. I _think_ that the solution would be to amend or remove the JS I point to above, but I'm not 100% sure.

**Comment by NateWr** [comment]
My suggested approach is to have the plugin provide the full SVG file content as a template variable named `$orcidSvg`. This could be provided to every template. Themers can then display it where they want with:

```
<a href="{$orcidUrl|escape}">
  {$orcidSvg}
  <span class="accessible-label-visually-hidden--most-themes-should-have-a-class-like-this">
    ORCID iD for {$authorName}
  </span>
</a>
```
