### ISSUE TITLE
[OPS] Pushing works information into researcher's ORCID record

### ISSUE THREAD

**Issue by alexxxmendonca** [pkp/orcidProfile#151]
**Is your feature request related to a problem? Please describe.**
ORCID Members that are using Member's API have the possibility to adding posted works into a researcher's ORCID record when their preprint gets posted.

However, currently the ORCID plugin for OPS doesn't do that.

**Describe the solution you'd like**
Allow preprint servers that are ORCID members to "push" works information into researcher's ORCID record following these instructions:

https://members.orcid.org/api/workflow/publishing-systems

**Comment by asmecher** [comment]
@withanage, I thought the plugin already supported this -- doesn't it?

**Comment by alexxxmendonca** [comment]
Hey @asmecher! Just want to add that maybe it does in OJS, but it's not doing it for preprints. As we don't use OJS for publishing articles, I can't tell if it works for OJS either.

**Comment by withanage** [comment]
@alexxxmendonca , I haven't tested in OPS, but in OJS  it works.

@ajnyga   have you tested this feature in OPS. Otherwise, I will have a look into it.

**Comment by alexxxmendonca** [comment]
@withanage I will fix the title and issue description.

Thanks!

**Comment by alexxxmendonca** [comment]
This has been fixed with the release of ORCID Profile plugin v1.1.2.18.

👍
