### ISSUE TITLE
Fatal error when used on site registration

### ISSUE THREAD

**Issue by ctgraham** [pkp/orcidProfile#164]
**Describe the bug**
Plugin causes 500 error on the registration page in the site context.

**To Reproduce**
1. Enable orcidProfile pluigin
2. Initiate registration within the site context
3. See error: `PHP Fatal error: Uncaught Error: Call to a member function getId() on null`

**Expected behavior**
Either registration using the orcidProfile plugin works within the site index, or the code fails gracefully to register without orcidProfile functionality in the site index.

**Additional context**
https://forum.pkp.sfu.ca/t/error-500-registration-page/57411/4?u=ctgraham

**Comment by asmecher** [comment]
Another report of this on the forum: https://forum.pkp.sfu.ca/t/after-upgrade-to-ojs-3-2-1-3-orcid-plugin-producing-fatal-error/65473/17

**Comment by asmecher** [comment]
@ctgraham, at a glance, it shouldn't be possible to enable the ORCID plugin site-wide. Do you know how you did that?

**Comment by ctgraham** [comment]
I think I just depended on the report from the forum rather than reproducing it locally.

**Comment by withanage** [comment]
@asmecher , it is actually possiblie to enable is sitewide using the config.inc.php


@ctgraham 


> Expected behavior
> Either registration using the orcidProfile plugin works within the site index, or the code fails gracefully to register without > orcidProfile functionality in the site index.


I would prefer  for disabing  the functionality for the site-index , cause the users generally do not need the orcid functionality f without context.

**Comment by withanage** [comment]
I have released the following plugin versions addressing this.

OJS 3.1 https://github.com/pkp/orcidProfile/releases/tag/v1_1_1-12
OJS 3.2 https://github.com/pkp/orcidProfile/releases/tag/v1_1_2-7

I will ask the forum users to do  functional tests.


OJS 3.3 will follow soon.

**Comment by withanage** [comment]
Since there aren't complains about the issue and most of the forum users confirm, I am closing this ticket and if there are any further requests, we can open a  new issue.
