### ISSUE TITLE
Support API Version 3.0

### ISSUE THREAD

**Issue by withanage** [pkp/orcidProfile#171]
#### ORCIP API Version 3

https://info.orcid.org/orcid-api-3-0-is-here/

|Product  | Version | Release | Submodule update | 
| ---  | --- | --- | --- | 
| OJS  | 3.3.1 | [1.1.2.17](https://github.com/pkp/orcidProfile/releases/tag/v1_1_2-17) |[#PR3130](https://github.com/pkp/ojs/pull/3130) 
| OJS  | 3.3.0 |[1.1.2.17](https://github.com/pkp/orcidProfile/releases/tag/v1_1_2-17) | [#PR3129](https://github.com/pkp/ojs/pull/3129)
| OJS  | 3.2.1 | [1.1.2.18](https://github.com/pkp/orcidProfile/releases/tag/v1_1_2-18) | [#PR3135](https://github.com/pkp/ojs/pull/3135)
| OPS  | 3.3.1 |[1.1.2.17](https://github.com/pkp/orcidProfile/releases/tag/v1_1_2-17) | [#PR154](https://github.com/pkp/ops/pull/154)
| OPS  | 3.3.0 | [1.1.2.17](https://github.com/pkp/orcidProfile/releases/tag/v1_1_2-17)| [#PR153](https://github.com/pkp/ops/pull/153)
| OPS  | 3.2.1 |[1.1.2.18](https://github.com/pkp/orcidProfile/releases/tag/v1_1_2-18)  | [#PR155](https://github.com/pkp/ops/pull/155)

 

After discussing with @asmecher  this feature will be added to orcidProfile plugin.

FYI @NateWr

**Comment by nuest** [comment]
I would add

- contributer roles (based on CRediT) to the list of potentially relevant features, see https://info.orcid.org/credit-for-research-contribution/

Though that certainly is not a small task as it would require quite a few extra forms for the author to fill out.

**Comment by withanage** [comment]
This issue will be closed and potential functional additions  will be  separately  addressed.
