### ISSUE TITLE
Website context login generates fatal error when orcidProfile is enabled

### ISSUE THREAD

**Issue by withanage** [pkp/orcidProfile#211]
**Describe the bug**

Issue is described in the  OJS 3.2.1 version of the plugin in #208

**Comment by asmecher** [comment]
@withanage, don't forget the release management to go with this; https://github.com/pkp/orcidProfile/milestone/1 should be updated to accurately reflect the issues that were resolved in it, and if it's been released, that milestone should be closed (and another created for the next minor issues).

**Comment by withanage** [comment]
@asmecher , Thanks for review. I  forgot that. Have closed the milestones and added new ones accordingly.
