### ISSUE TITLE
Unable to complete submission due to failed attempt to convert LazyCollection into array

### ISSUE THREAD

**Issue by touhidurabir** [pkp/orcidProfile#224]
**Describe the bug**
New Submission can not be completed or proceed to next step because of a failed attempt to convert a LazyCollection into an array . This cause to halt the proceeding to next step and those `Fatal Error`

**To Reproduce**
1. Login as Author
2. Create a new submission
3. Proceed to the step 3 that is `Enter Metadata` stage.
4. Fill up the required details and click on `Save and Continue`. 
5. See that the loading does not go away and neither can be proceed to next step which indicate an inter exception/error.

**Screenshots**
![CleanShot 2022-10-23 at 21 01 35](https://user-images.githubusercontent.com/2587979/197399756-32b4a22d-0509-4709-bcec-a3b0d4691ce5.png)

**Additional context**

The cause of the issue lies at https://github.com/pkp/orcidProfile/blob/main/OrcidProfilePlugin.inc.php#L543-L553 as the `$authors` is a LazyCollection which can not be directly used or converted into an array . 

The following error trace is getting registered to the system/php log

```
PHP Fatal error:  Uncaught Error: Cannot use object of type Illuminate\Support\LazyCollection as array in /Users/abir/Sites/code/ojs-main/plugins/generic/orcidProfile/OrcidProfilePlugin.inc.php:543
Stack trace:
#0 [internal function]: OrcidProfilePlugin->handleSubmissionSubmitStep3FormExecute('submissionsubmi...', Array)
#1 /Users/abir/Sites/code/ojs-main/lib/pkp/classes/plugins/Hook.php(139): call_user_func_array(Array, Array)
#2 /Users/abir/Sites/code/ojs-main/lib/pkp/classes/plugins/Hook.php(112): PKP\plugins\Hook::run('submissionsubmi...', Array)
#3 /Users/abir/Sites/code/ojs-main/lib/pkp/classes/form/Form.php(337): PKP\plugins\Hook::call('submissionsubmi...', Array)
#4 /Users/abir/Sites/code/ojs-main/lib/pkp/classes/submission/form/PKPSubmissionSubmitStep3Form.php(130): PKP\form\Form->execute()
#5 /Users/abir/Sites/code/ojs-main/lib/pkp/pages/submission/PKPSubmissionHandler.php(199): PKP\submission\form\PKPSubmissionSubmitStep3Form->execute()
#6 [internal function]: PKP\pages\submission\PKPSubmissionHandler->saveStep(Array, Object(APP\core\Request))
#7 /Users/abir/Sites/code/ojs-main/lib/pkp/classes/core/PKPRouter.php(465): call_user_func(Array, Array, Object(APP\core\Request))
#8 /Users/abir/Sites/code/ojs-main/lib/pkp/classes/core/PKPPageRouter.php(308): PKP\core\PKPRouter->_authorizeInitializeAndCallRequest(Array, Object(APP\core\Request), Array, false)
#9 /Users/abir/Sites/code/ojs-main/lib/pkp/classes/core/Dispatcher.php(163): PKP\core\PKPPageRouter->route(Object(APP\core\Request))
#10 /Users/abir/Sites/code/ojs-main/lib/pkp/classes/core/PKPApplication.php(379): PKP\core\Dispatcher->dispatch(Object(APP\core\Request))
#11 /Users/abir/Sites/code/ojs-main/index.php(21): PKP\core\PKPApplication->execute()
#12 /Users/abir/.composer/vendor/laravel/valet/server.php(234): require('/Users/abir/Sit...')
#13 {main}
  thrown in /Users/abir/Sites/code/ojs-main/plugins/generic/orcidProfile/OrcidProfilePlugin.inc.php on line 543
```

**Comment by touhidurabir** [comment]
@asmecher can you please review the PR at https://github.com/pkp/orcidProfile/pull/225

**Comment by touhidurabir** [comment]
@asmecher sure .

**Comment by withanage** [comment]
@touhidurabir 

my apologies for coming for this really late.  As the submission wizard has changed now for 3.4 , we do not have the step to execute the form. But I have adapted your suggestion here

https://github.com/pkp/orcidProfile/pull/248

and  created a seperate PR not to conflict with the latest changes.
