### ISSUE TITLE
Broken link to orcid id icon on What is ORCID? info page

### ISSUE THREAD

**Issue by tmrozewski-york** [pkp/orcidProfile#230]
The link to the Orcid ID icon on the What is ORCID? page (the front-end page created by the plugin) appears to be broken. I have verified this on two different instances of OJS:

https://refuge.journals.yorku.ca/index.php/refuge/orcidapi/about
https://witness.journals.yorku.ca/index.php/default/orcidapi/about

The broken image link is https://orcid.org/sites/default/files/images/orcid_16x16(1).gif

Both sites running OJS 3.3.0.13, ORCID Profile plugin 1.1.3.4

**Comment by withanage** [comment]
@tmrozewski-york 

Thanks for the link. I have updated the translations and pushed into the repo. Will add in the next release in a couple of weeks
