### ISSUE TITLE
ORCID icon displayed for unauthenticated IDs

### ISSUE THREAD

**Issue by felixhelix** [pkp/orcidProfile#232]
**Describe the bug**
If ORCID IDs have been assigned to contributors before the plugin is activated, on activation the green ORCID icon is shown on the article details page without authentication.

**To Reproduce**
1. Deactivate the orcidProfile plugin
2. Enter ORCID ID for a contributor in the article publication stage
3. Publish Article
4. Activate orcidProfile plugin
5. Go to details page
6. See green ORCID icon

**Expected behavior**
As the ORCID id has not been authorized, it should be displayed without the green ORCID icon.

**Screenshots**

I used a valid but non-existing ORCID id ( (see https://support.orcid.org/hc/en-us/articles/360006897674-Structure-of-the-ORCID-Identifier)

Before activation:
![image](https://user-images.githubusercontent.com/5220783/217298266-c6c035f5-0b1c-4c28-8cd4-e640159a126a.png)

After activation:
![image](https://user-images.githubusercontent.com/5220783/217298413-312713e1-ba0f-49a1-ac5d-ab7aeb93949b.png)

**Additional context**
OJS 3.3.0.8
orcidProfile 1.1.3.4

**Comment by withanage** [comment]
## PR s created for both OJS and OPs

- https://github.com/pkp/ops/pull/468
- https://github.com/pkp/ojs/pull/3758

**Comment by asmecher** [comment]
I've merged both PRs -- thanks, @withanage!
