### ISSUE TITLE
OJS "thank reviewer" process frozen with public API.

### ISSUE THREAD

**Issue by dagosalas** [pkp/orcidProfile#233]
**Describe the bug**
Using Public API on OJS3.3.x, at the moment of "thank reviewer", the OJS it stays cycled and does not respond.
When reviewing the error LOG, there are connection errors (error 500) to the ORCID API trying to push the reviewer's record. Which shouldn't be since the public API doesn't do record pushing, just members.

**To Reproduce**
Go to a round of review, and with a review done, click on thank reviewer.
The reviewer must have validated your ORCID initially.

**Expected behavior**
When clicking on "thank reviewer", a window should appear where OJS sends a message to the reviewer.

**Additional context**
This error only appears with OJS using the public API plugin.
With the member API I have had no problems.

The only solution at the moment is to unlink the ORCID from the reviewer and now to proceed normally.

**Comment by withanage** [comment]
@dagosalas  the thank-reviewer should only function with member api.

**Comment by dagosalas** [comment]
That's correct, but the plugin is currently not identifying if the journal uses the member API or the public API and tries to push the data. The plugin should identify what type of API is being used to perform that function with the reviewers.

**Comment by withanage** [comment]
@dagosalas  the above commit shoud fix it for 3.4

Let me down-grade it for  3.3 . I will let you know.

**Comment by withanage** [comment]
Added a fix for this  into my dev branch. If you  can install this and confirm , it would be great!
Otherwise, I will release this in the next release.


https://github.com/withanage/orcidProfile/tree/issue233-3-3_0

**Comment by withanage** [comment]
@dagosalas merged to 3.3 branch
