### ISSUE TITLE
Linking profile to orcid gives errorlog and blank page

### ISSUE THREAD

**Issue by Jannik-Lappe** [pkp/orcidProfile#240]
**Describe the bug**
Last week we updated our OJS journals and their plugins to the latest version (ojs 3.3.0-14 and orcidprofile 1.1.3.4)
the orcidprofile plugin was already up-to-date and worked fine until the update.
Now when linking an orcid profile, the users get a white page after trying to link and logging into orcid.

**To Reproduce**
1. Go to 'profile->public'
2. click on link profile
3. log into orcid
4. get white page

**Expected behavior**
user gets e-mail with link to confirm the action

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04 / Windows 10
 - Browser: Firefox
 - Version: 88.0

**Additional context**

apache error log:
```
PHP Fatal error:  Uncaught TypeError: Carbon\\Carbon::setLastErrors(): Argument #1 ($lastErrors) must be of type array, bool given, called in /path/to/ojs/lib/pkp/lib/vendor/nesbot/carbon/src/Carbon/Traits/Creator.php on line 96 and defined in /path/to/ojs/lib/pkp/lib/vendor/nesbot/carbon/src/Carbon/Traits/Creator.php:897
Stack trace:
#0 /path/to/ojs/lib/pkp/lib/vendor/nesbot/carbon/src/Carbon/Traits/Creator.php(96): Carbon\\Carbon::setLastErrors()
#1 /path/to/ojs/lib/pkp/lib/vendor/nesbot/carbon/src/Carbon/Traits/Creator.php(250): Carbon\\Carbon->__construct()
#2 /path/to/ojs/plugins/generic/orcidProfile/pages/OrcidHandler.inc.php(159): Carbon\\Carbon::now()
#3 /path/to/ojs/plugins/generic/orcidProfile/pages/OrcidHandler.inc.php(139): OrcidHandler->_setOrcidData()
#4 /path/to/ojs/lib/pkp/classes/core/PKPRouter.inc.php(395): OrcidHandler->orcidAuthorize()
#5 /path/to/ojs/lib/pkp/classes/core/PKPPageRouter.inc.php(246): PKPRouter->_authorizeInitializeAndCallRequest()
#6 /path/to/ojs/lib/pkp/classes/core/Dispatcher.inc.php(144): PKPPageRouter->route()
#7 /path/to/ojs/lib/pkp/classes/core/PKPApplication.inc.php(362): Dispatcher->dispatch()
#8 /path/to/ojs/index.php(68): PKPApplication->execute()
#9 {main}
  thrown in /path/to/ojs/lib/pkp/lib/vendor/nesbot/carbon/src/Carbon/Traits/Creator.php on line 897, referer: https://orcid.org/
```

Thank you for your help
Jannik

**Comment by withanage** [comment]
@Jannik-Lappe 

Error indicates that you have not installed Carbon on your OJS server.


Have you run 

composer --working-dir=lib/pkp install or 

composer --working-dir=lib/pkp update

to update the vendor libraries?

**Comment by Jannik-Lappe** [comment]
Carbon is installed. I haven't run the composer because it was a clean update.
I'll try to update the vendor libs and report back.

**Comment by Jannik-Lappe** [comment]
68 packages were updated.
It works now.
