### ISSUE TITLE
DOI is not included when work is exported

### ISSUE THREAD

**Issue by eddoff** [pkp/orcidProfile#258]
**Describe the bug**
When an article is published the work is transferred to the ORCID profile. But the article DOI is not transferred. If the ORCID user harvest from Crossref two records will be created in the ORCID profile. I guess it is due to that the DOI to the article is not transferred. 
From the log only the DOI of the issue is exported, and the URL to the artilce, not the DOI to the article:
    "external-ids": {
        "external-id": [{
                "external-id-type": "doi",
                "external-id-value": "10.3384\/de-ethica.2001-8819.2372",
                "external-id-url": {
                    "value": "https:\/\/doi.org\/10.3384\/de-ethica.2001-8819.2372"
                },
                "external-id-relationship": "part-of"
            }, {
                "external-id-type": "uri",
                "external-id-value": "https:\/\/de-ethica.com\/article\/view\/4357",
                "external-id-relationship": "self"
            }, {
                "external-id-type": "issn",
                "external-id-value": "2001-8819",
                "external-id-relationship": "part-of"
            }
        ]
    },
This is how it looks in the ORCID profile:
![bild](https://user-images.githubusercontent.com/41610473/227151992-b38ae0da-4034-49e5-82a5-c0c1cb8c2522.png)

**To Reproduce**
1. Activate ORCID member API
2. Setup the loggin to "All"
3. Publish an article with a user that has a validated ORCID
4. Check the log
5. Check the ORCID profile

**Expected behavior**
that the DOI to the article is included in the export of the plugin.

**Desktop (please complete the following information):**
 - OS server: CENTOS 
 - OJS: 3.3.0-13
 - ORCID plugin: 1.1.3.4

Best regards, Eddoff

**Comment by withanage** [comment]
Hi @eddoff 

I have relaeased the version 1.1.3.6  with the addition of the url as doi.

**Comment by eddoff** [comment]
> Hi @eddoff
> 
> I have relaeased the version 1.1.3.6 with the addition of the url as doi.

Thanks! Great news! 

Is it possible to resend already published articles to ORCID now, so that the records are updated with DOI:s?

**Comment by withanage** [comment]
@eddoff sure!

**Comment by eddoff** [comment]
> @eddoff sure!

How can I do that? Do I have to unpublish-republish those articles, or could it be done in another batch-wise way?

**Comment by withanage** [comment]
@eddoff  currenlty the only way, I know is creating a new version or unpublish and republish
