### ISSUE TITLE
Plugin page keeps loading after installing orcidProfile

### ISSUE THREAD

**Issue by drfurtado** [pkp/orcidProfile#282]
**Describe the bug**
The plugin page keeps loading after I install the `orcidProfile` plugin.
OJS: 3.3.0.13
Desktop: Edge or Safari up-to-date

![Screenshot 2023-10-02 at 5 55 50 PM](https://github.com/pkp/orcidProfile/assets/9524571/c7b86313-5945-4f69-9bfe-5fe89080abf8)

**Comment by asmecher** [comment]
@drfurtado, can you post this on the support forum (https://forum.pkp.sfu) along with any relevant entries from your PHP error log? That's the best place to get support.
