### ISSUE TITLE
getManager call is deprecated without request

### ISSUE THREAD

**Issue by trp89** [pkp/orcidProfile#283]
https://github.com/pkp/orcidProfile/blob/c3375e3809468c53a104021d397f44daabdf7c13/OrcidProfilePlugin.php#L994

https://github.com/pkp/pkp-lib/blob/4aad70b0cf437b174b2c9922ef50b886aeab7a98/classes/template/PKPTemplateManager.php#L1382-L1385

Note that this will cause a hard fail if deprecation warnings is turned on

**Comment by asmecher** [comment]
@trp89, the attached commit will resolve the issue.
