### ISSUE TITLE
Not view in plugins after upgraded

### ISSUE THREAD

**Issue by manaim2112** [pkp/orcidProfile#289]
**Describe the bug**
Current Default OJS 3.3.0 , and I upgrade to latest version plugin orcid 
Upgraded, but after upgraded in not view in plugin

**Screenshots**

![Screenshot_20231015-081450.png](https://github.com/pkp/orcidProfile/assets/49584629/2c51c419-26d4-4e6f-87bd-1a6e1a61faad)

**Comment by withanage** [comment]
@manaim2112 
I am not so clear about the problem. Can you please give some more details ?

**Comment by manaim2112** [comment]
> @manaim2112 
> I am not so clear about the problem. Can you please give some more details ?

In page plugins -> generic , not found OrcidPlugin.

But, in plugin gallery has updated

**Comment by withanage** [comment]
We recommend updating it using the plugin gallery to avoid  any issues. Can you do it direcly be plugin gallery?

**Comment by manaim2112** [comment]
![image](https://github.com/pkp/orcidProfile/assets/49584629/e4054b1e-560b-45fe-b524-bda99a0f1401)
iam updated version
how to previous plugin back ?

**Comment by withanage** [comment]
I  would remove the git version from the server and  install the  version from the plugin gallery, then you do not have incompatibilities

**PLEASE WRITE DOWN THE ORICD API CREDENTAILS !**

**Comment by manaim2112** [comment]
done, thanks a lot.

**Comment by bozana** [comment]
Can this issue be closed?
