### ISSUE TITLE
Connect button missing on register page

### ISSUE THREAD

**Issue by juanCure** [pkp/orcidProfile#294]
**Describe the bug**
I have installed a OJS v3.3.0.15 and upgraded the orcidProfile plugin to v1.1.3.10 and set up the plugin with the Sandbox Public API, and I have noticed that the **Create or Connect your ORCID ID** button is missing on the register a new user's account page. The doubt here is, this is either a expected feature or a bug?
 
**To Reproduce**
1. Install OJS v3.3.0.15
2. Upgrade the orcidProfile module from plugin gallery
3. Set up the orcidProfile module to use the Sandbox Public API
4. Go to Register page
![10 register_page](https://github.com/pkp/orcidProfile/assets/1661533/c85c7f19-4ab8-44c7-9b26-e4433cdedf9e)

In another way, I have noticed this button appears in the Profile > Public page.
![11 profile_page](https://github.com/pkp/orcidProfile/assets/1661533/1312158f-3be0-42e1-9901-2a1c673d7b1c)

The enviroment of the server is:
OS: Centos 7
PHP v7.4.33
MySQL 8.0.23

**Comment by asmecher** [comment]
Cross-posted: https://forum.pkp.sfu.ca/t/ojs-3-3-0-11-orcid-button-missing/81273/5

**Comment by ewhanson** [comment]
@asmecher could you have a look? It was a quick fix to add it back in. Not an issue in `stable-3_4_0`. Thanks!

PR:

- #294

**Comment by ewhanson** [comment]
Thanks for the report @juanCure! Working on getting a fix for this in.

**Comment by asmecher** [comment]
@ewhanson, the PR link above is actually back to this same issue! Can you correct?

**Comment by ewhanson** [comment]
> @ewhanson, the PR link above is actually back to this same issue! Can you correct?

Oops! Should be correct above now. Thanks!

**Comment by asmecher** [comment]
Merged, thanks! I'm guessing this needs forward-porting too, right?

**Comment by ewhanson** [comment]
> Merged, thanks! I'm guessing this needs forward-porting too, right?

Thanks! Nope, it shouldn't. I double checked in stable_3_4_0 and main and the button was present. It seems like it was accidentally removed in stable_3_3_0 at some point.

**Comment by asmecher** [comment]
Perfect, thanks!

**Comment by jnugent** [comment]
Hi everyone,  with the re-addition of the connect button on the register page we are seeing a strange google recaptcha error now, with some debugging printed into the console.  This comes back from Google (this locale key is not in the OJS codebase I don't think)

```
##common.captcha.error.timeout-or-duplicate##
The form could not be submitted. You may have been logged out. Please reload the page and try again.
```

and then nothing happens.   We get this in the browser JS console:

```ORCID Logged In: false [register:177:25]```

If this is indeed broken, the feature should probably come back out.  Dulip mentioned that it doesn't do much anyway.

**Comment by ewhanson** [comment]
Hey @jnugent, it does seem like it was causing an issue. I've gone ahead and undone the change (PR: #303).

**Comment by bozana** [comment]
@jnugent, oh, great that you have reported it -- there was a user in the forum having problems with google re-captcha, when installing the new orcid version...
But, how comes actually that this makes a problem? Any idea?

**Comment by bozana** [comment]
Hi @jnugent, do you maybe also have an 3.4 installation together with re-captcha? The ORCID button is also in 3.4...

**Comment by SupremeDimeji** [comment]
Hi @ewhanson @asmecher, 
Is there any solution to the missing Connect ID button? Or is it permanently removed now?

I'm having the same issue on ojs 3.3. orcid plugin v1_1_3-12
Thanks

**Comment by ewhanson** [comment]
Hi @SupremeDimeji, the Connect ID button has not permanently been removed, but there are a few issues that need to be addressed before we add the button back in. Thanks.
