### ISSUE TITLE
Unable to submit review data with multilingual submission

### ISSUE THREAD

**Issue by jnugent** [pkp/orcidProfile#322]
**Describe the bug**
we've a client using OJS 3.3, with a member API account. They are trying to integrate the reviewer thanking component and the review submission to ORCID is failing with

```
2024-10-16 11:18:51.921 INFO Publication fail: {"response-code":400,"developer-message":"400 Bad request: invalid JSON - cvc-complex-type.2.4.a: Invalid content was found starting with element '{\"http://www.orcid.org/ns/common\":translated-title}'. One of '{\"http://www.orcid.org/ns/common\":title}' is expected.","user-message":"Invalid JSON.","error-code":9047,"more-info":"https://members.orcid.org/api/resources/troubleshooting"}
```

Looking at the code it seems that the translated-title stuff is added to the payload if the default language is not the language of the submission.  I'm not really sure why the translated title is showing up ahead of the regular title.   All of the title metadata is filled in in all locales.

I can provide access to the installation and the orcid.log if necessary.

OJS 3.3

**Comment by ewhanson** [comment]
Thanks @jnugent, I don't remember the exact details, but I had run into something similar when moving the plugin into the main library for 3.5. I'll have a look and get it fixed. I shouldn't need anything specific, but if I do need to see the

**Comment by ewhanson** [comment]
PRs:

- `stable-3_3_0`: #324
- `stable-3_4_0`: #325
- `main` (ojs): pkp/ojs#4544

**Comment by ewhanson** [comment]
@bozana, could you have a look at these PRs? They update the needed code to send along titles/translated titles. Titles are always required and we will now send translated titles where they exist. I have confirmed that they do not appear as part of the metadata displayed in the reviewers ORCID profile. Thanks!

**Comment by bozana** [comment]
Hi @ewhanson, I took a look and left a comment and a question in the PR for the main branch, but those are relevant to all 3 :-)
Thanks!

**Comment by ewhanson** [comment]
Merged!
